version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
  backend:
    build: ./TODO_List
    privileged: true
    ports:
      - 8080:8080
    command: 
      bash -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py create_user &&
      python3 manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db